# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/transport/proto/message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'src/transport/proto/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!src/transport/proto/message.proto\x12\x16secureasr.transport.v1\"4\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\xf2\x01\n\x05Value\x12\x36\n\x0ctensor_value\x18\x01 \x01(\x0b\x32\x1e.secureasr.transport.v1.TensorH\x00\x12\x38\n\rmapping_value\x18\x02 \x01(\x0b\x32\x1f.secureasr.transport.v1.MappingH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x42\x06\n\x04kind\"B\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.secureasr.transport.v1.Value\"9\n\x07Mapping\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.secureasr.transport.v1.Entry\"\xcb\x01\n\x07Message\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\x03\x12\x0c\n\x04step\x18\x04 \x01(\x03\x12\x30\n\x07payload\x18\x05 \x01(\x0b\x32\x1f.secureasr.transport.v1.Mapping\x12\x10\n\x08protocol\x18\x06 \x01(\t\x12\x18\n\x10protocol_version\x18\x07 \x01(\r\x12\x12\n\nrequest_id\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65\x61\x64line_at\x18\t \x01(\x01\"\x0b\n\tSendReply2W\n\tTransport\x12J\n\x04Send\x12\x1f.secureasr.transport.v1.Message\x1a!.secureasr.transport.v1.SendReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.transport.proto.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=61
  _globals['_TENSOR']._serialized_end=113
  _globals['_VALUE']._serialized_start=116
  _globals['_VALUE']._serialized_end=358
  _globals['_ENTRY']._serialized_start=360
  _globals['_ENTRY']._serialized_end=426
  _globals['_MAPPING']._serialized_start=428
  _globals['_MAPPING']._serialized_end=485
  _globals['_MESSAGE']._serialized_start=488
  _globals['_MESSAGE']._serialized_end=691
  _globals['_SENDREPLY']._serialized_start=693
  _globals['_SENDREPLY']._serialized_end=704
  _globals['_TRANSPORT']._serialized_start=706
  _globals['_TRANSPORT']._serialized_end=793
# @@protoc_insertion_point(module_scope)
